Week4作業繳交
JoycexChan/taipei-day-trip pull request #5
Opened 2024-06-23 08:43 UTC by JoycexChan

陳雅君
http://54.234.123.146:8000/
http://54.234.123.146:8000/attraction/10

2024-06-23 13:06 UTC, cwpeng requested changes
Response format should align with User API specs.

2024-06-23 16:24 UTC, JoycexChan commented
> Response format should align with User API specs.

老師抱歉，雖然目前已經處理好（Response format should align with User API specs)，回應如下，但出現了一個前端登入錯誤還沒修好，它沒有辦法儲存狀態，我再除錯一下，盡量半夜完成。

POST /api/user
[1] code 200
![image](https://github.com/JoycexChan/taipei-day-trip/assets/163320736/72053643-f338-4d90-a2b1-55d0deb7f4eb)
[2] code 400
![image](https://github.com/JoycexChan/taipei-day-trip/assets/163320736/84822dc0-535f-466a-8ff6-ca74d2dd236a)
[3] code 500 (利用name超過255字製造錯誤)
![image](https://github.com/JoycexChan/taipei-day-trip/assets/163320736/d4bd7bca-505c-4504-bf39-fbe0bae00882)

GET /api/user/auth
[1] null(未登入)
![image](https://github.com/JoycexChan/taipei-day-trip/assets/163320736/cd456c3d-41f4-49d5-99ba-590bd0b66450)
[2]已登入的會員資料
![image](https://github.com/JoycexChan/taipei-day-trip/assets/163320736/08f372c4-f6d3-44a1-8859-2132cd54fd7f)

PUT /api/user/auth
[1] code 200
![image](https://github.com/JoycexChan/taipei-day-trip/assets/163320736/11f48a3b-24da-4a0c-9301-4f82b573eb04)

[2] code 400
![image](https://github.com/JoycexChan/taipei-day-trip/assets/163320736/55d00e6c-7d02-4a67-b2dd-f985c256375c)

[3] code 500（故意造成錯誤來觸發500錯誤)
![image](https://github.com/JoycexChan/taipei-day-trip/assets/163320736/e426c0ba-6938-46c9-8053-ab8c1f2a72c5)

2024-06-23 18:37 UTC, cwpeng commented
Just ask for review after you fixed it.

2024-06-23 21:43 UTC, JoycexChan commented
> Just ask for review after you fixed it.

陳雅君
http://54.234.123.146:8000/
http://54.234.123.146:8000/attraction/10

好的
做完了～～～～～
再麻煩老師檢查了，謝謝

2024-06-24 03:47 UTC, cwpeng approved these changes
OK. Done.

2024-06-28 06:14 UTC, merged